apiVersion: v1
kind: PersistentVolume
metadata:
  name: messing-data-pv
  namespace: messing
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/messing"